/* AUTHENTICATION */
/* LOGIN */
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

/* STATUS */
export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";

/* LOGOUT */
export const AUTH_LOGOUT = "AUTH_LOGOUT";

/* REGISTER */
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";

/* Card */
export const CARD_POST = "CARD_POST";
export const CARD_POST_SUCCESS = "CARD_POST_SUCCESS";
export const CARD_POST_FAILURE = "CARD_POST_FAILURE";

export const CARD_LIST = "CARD_LIST";
export const CARD_LIST_SUCCESS = "CARD_LIST_SUCCESS";
export const CARD_LIST_FAILURE = "CARD_LIST_FAILURE";
