/* AUTHENTICATION */
/* LOGIN */
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

/* STATUS */
export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";

/* LOGOUT */
export const AUTH_LOGOUT = "AUTH_LOGOUT";

/* REGISTER */
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";

/* Idiom */
export const IDIOM_POST = "IDIOM_POST";
export const IDIOM_POST_SUCCESS = "IDIOM_POST_SUCCESS";
export const IDIOM_POST_FAILURE = "IDIOM_POST_FAILURE";

export const IDIOM_LIST = "IDIOM_LIST";
export const IDIOM_LIST_SUCCESS = "IDIOM_LIST_SUCCESS";
export const IDIOM_LIST_FAILURE = "IDIOM_LIST_FAILURE";